"use client";

import { useEffect, useMemo, useRef, useState } from "react";
type ManualId = "english" | "seed" | "yoruba";
type PackId = "english" | "yoruba";

const englishWeeks=[73,78,83,88,92,94,99,104,109,114,115,119,124,129,134,136,141,146,151,156,158,163,167,172,176,177,182,187,192,197,199,204,209,214,219,221,226,232,237,242,244,249,254,259,264,265,270,275,280,281,285];
const seedWeeks=[39,45,54,61,68,72,80,89,96,103,107,115,123,130,137,140,148,156,164,171,175,183,190,198,204,208,215,222,230,236,240,246,252,258,264,268,275,281,288,293,297,304,311,319,325,329,336,341,348,352,358];
const yorubaWeeks=englishWeeks.map((p,i)=>Math.max(42,Math.min(258,p-(i<35?31:i<45?30:27))));

const manuals={
  english:{id:"english" as ManualId,short:"English",title:"31st Convention & Annual Bible Study Manual",subtitle:"An Exceeding Great Army",audience:"Adult & general fellowship",cover:"/tacef-english-cover.jpg",pdf:"/manuals/tacef-2026-english.pdf",pages:324,weekPages:englishWeeks,overview:"The complete original 2026 Convention and 2026/2027 Annual Bible Study Manual, including convention instructions, hymns, converts' lessons, weekly studies, daily devotionals and the TACEF information pack.",topics:["Joshua","Ephesians","Revival","Consecration","Spiritual Warfare"]},
  seed:{id:"seed" as ManualId,short:"Seed of Purpose",title:"Seed of Purpose Manual",subtitle:"Growing God's Exceeding Great Army",audience:"Children & young disciples",cover:"/tacef-seed-cover.jpg",pdf:"/manuals/tacef-2026-seed-of-purpose.pdf",pages:379,weekPages:seedWeeks,overview:"The complete original Seed of Purpose convention and weekly study manual, with Bible lessons, memory verses, daily devotionals, prayers, class activities and the seven pillars of TACEF Seed of Purpose.",topics:["Children","Dry Bones","Character","Obedience","Activities","Prayer"]},
  yoruba:{id:"yoruba" as ManualId,short:"Yorùbá",title:"Ìwé Ètò Ìpàgọ́ àti Ẹ̀kọ́ Ìpèjọpọ̀",subtitle:"Ìkọ̀ Ọmọ-ogun Nláńlá",audience:"Yorùbá language fellowship",cover:"/tacef-yoruba-cover.jpg",pdf:"/manuals/tacef-2026-yoruba.pdf",pages:282,weekPages:yorubaWeeks,overview:"Gbogbo ọ̀rọ̀ inú ìwé ìtọ́sọ́nà ìpàgọ́ àti ẹ̀kọ́ Bíbélì TACEF 2026/2027 ní èdè Yorùbá, pẹ̀lú ẹ̀kọ́ ọ̀sẹ̀, ẹ̀kọ́ ojoojúmọ́, àdúrà, orin àti ìsọjí.",topics:["Yorùbá","Jóṣúà","Ìsọjí","Àdúrà","Ìgbọràn"]}
};

const informationPacks={
  english:{id:"english" as PackId,language:"English",title:"TACEF Information Pack",manualId:"english" as ManualId,start:290,end:324,code:"EN",description:"Membership, ministries, programmes, platforms, contacts and essential information about TACEF."},
  yoruba:{id:"yoruba" as PackId,language:"Yorùbá",title:"Àwọn Ìfitónilétí TACEF",manualId:"yoruba" as ManualId,start:263,end:282,code:"YO",description:"Àwọn ìfitónilétí nípa ọmọ ẹgbẹ́, iṣẹ́-ìránṣẹ́, ètò, ìpàdé àti àwọn ọ̀nà ìbánisọ̀rọ̀ TACEF."}
};

const featuredTitles=["Becoming a Trusted Soldier in the Lord's Army","A Kingdom Army Built in Courage and Wisdom","Arising into God's Ordained Assignment","Possessing the Land for the Lord","Tarry Week for Reflection and Prayer","The Power of Redemption to Save All Men","Moving by Divine Leading into New Territories","Preserving Revival Testimonies","Consecration Before Victory","Submitting the Battle to Christ","Winning God's Battle God's Way","How Hidden Sin Brings Defeat","Rising Again After Failure"];
const titleForWeek=(week:number)=>featuredTitles[week-1]||`Annual Bible Study — Week ${week}`;

function SinglePdfPage({src,page,direction,zoom}:{src:string;page:number;direction:"next"|"prev";zoom:number}){
  const frameRef=useRef<HTMLDivElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const [document,setDocument]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
  useEffect(()=>{let active=true;let task:any;let loadedDocument:any;(async()=>{try{setLoading(true);setError(false);const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc="/pdf.worker.min.mjs";const response=await fetch(src);if(!response.ok)throw new Error(`PDF request failed: ${response.status}`);const data=new Uint8Array(await response.arrayBuffer());task=pdfjs.getDocument({data});loadedDocument=await task.promise;if(active)setDocument(loadedDocument)}catch(err){console.error("PDF load failed",err);if(active)setError(true)}})();return()=>{active=false;setDocument(null);if(loadedDocument)loadedDocument.destroy();else task?.destroy?.()}},[src]);
  useEffect(()=>{if(!document||!canvasRef.current)return;let renderTask:any;let stopped=false;(async()=>{try{setLoading(true);setError(false);const currentPage=await document.getPage(page);if(stopped)return;const pixelRatio=Math.min(window.devicePixelRatio||1,2);const cssScale=zoom/100;const viewport=currentPage.getViewport({scale:cssScale*pixelRatio});const canvas=canvasRef.current;if(!canvas)return;canvas.width=Math.floor(viewport.width);canvas.height=Math.floor(viewport.height);canvas.style.width=`${Math.floor(viewport.width/pixelRatio)}px`;canvas.style.height=`${Math.floor(viewport.height/pixelRatio)}px`;const context=canvas.getContext("2d",{alpha:false});if(!context)return;renderTask=currentPage.render({canvasContext:context,viewport});await renderTask.promise;if(!stopped)setLoading(false)}catch(err:any){if(err?.name!=="RenderingCancelledException"&&!stopped){console.error("PDF render failed",err);setError(true)}}})();return()=>{stopped=true;renderTask?.cancel?.()}},[document,page,zoom]);
  return <div ref={frameRef} className="single-page-frame" aria-live="polite"><div key={`${page}-${direction}`} className={`canvas-sheet page-turn-${direction}`}><canvas ref={canvasRef}/>{loading&&!error&&<div className="page-loading"><span/>Preparing page {page}…</div>}{error&&<div className="page-error"><b>This page could not be displayed.</b><button onClick={()=>window.location.reload()}>Try again</button></div>}</div></div>
}

export default function Home(){
  const [selected,setSelected]=useState<ManualId|null>(null);const [readingPack,setReadingPack]=useState<PackId|null>(null);const [pdfPage,setPdfPage]=useState(1);const [week,setWeek]=useState(1);const [direction,setDirection]=useState<"next"|"prev">("next");const [search,setSearch]=useState("");const [overview,setOverview]=useState<ManualId|null>(null);const [zoom,setZoom]=useState(125);
  const manualList=Object.values(manuals);const today=new Date();const start=new Date("2026-08-31T00:00:00");const daysFromStart=Math.floor((today.getTime()-start.getTime())/86400000);const activeWeek=Math.max(1,Math.min(51,Math.floor(daysFromStart/7)+1));const dateMessage=daysFromStart<0?"Week 1 begins tomorrow":`Current study: Week ${activeWeek}`;
  const results=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return[];return manualList.filter(m=>[m.title,m.subtitle,m.audience,m.overview,...m.topics].join(" ").toLowerCase().includes(q))},[search]);
  const goToPage=(target:number)=>{if(!selected)return;const pack=readingPack?informationPacks[readingPack]:null;const minimum=pack?.start??1;const maximum=pack?.end??manuals[selected].pages;const safe=Math.max(minimum,Math.min(maximum,target));if(safe===pdfPage)return;setDirection(safe>pdfPage?"next":"prev");setPdfPage(safe)};
  const goToWeek=(id:ManualId,targetWeek:number)=>{const m=manuals[id];const safe=Math.max(1,Math.min(51,targetWeek));setReadingPack(null);setSelected(id);setWeek(safe);setDirection("next");setPdfPage(m.weekPages[safe-1]||m.weekPages[0]);setOverview(null)};
  const openBook=(id:ManualId)=>goToWeek(id,activeWeek);
  const openInformationPack=(id:PackId)=>{const pack=informationPacks[id];setReadingPack(id);setSelected(pack.manualId);setDirection("next");setPdfPage(pack.start);setOverview(null)};
  const closeReader=()=>{setSelected(null);setReadingPack(null)};

  return <main>
    <header className="site-header"><a className="official-brand" href="#home"><img src="/tacef-logo.png" alt="The African Church Evangelical Fellowship"/></a><nav><a href="#home">Home</a><a href="#manuals">Manuals</a><a href="#information-pack">Information Pack</a><a href="#search">Search</a></nav><div className="header-mark">2026 / 2027</div></header>
    <section className="hero" id="home"><div className="hero-copy"><span className="red-rule"/><h1>AN EXCEEDING<br/>GREAT ARMY</h1><blockquote>“So the breath came into them, and they lived, and stood up <b>upon their feet, an exceeding great army.</b>” <span>— Ezekiel 37:10</span></blockquote><button className="primary" onClick={()=>openBook("english")}>Open current study <span>→</span></button></div><div className="hero-poster"><div className="poster-frame"><img src="/tacef-english-cover.jpg" alt="TACEF An Exceeding Great Army manual cover"/></div><div className="hero-current"><span>{today.getDate()} {today.toLocaleString("en-GB",{month:"short"})} {today.getFullYear()}</span><b>{dateMessage}</b><button onClick={()=>openBook("english")}>Go to Week {activeWeek} →</button></div></div></section>
    <section className="manual-section" id="manuals"><div className="section-title"><div><p className="eyebrow">The complete manual library</p><h2>Choose your book</h2></div><p>Every original page is included. Open at the current week, select any of the 51 weeks, or navigate directly to any page.</p></div><div className="book-shelf">{manualList.map((m,i)=><article className="book-item" key={m.id}><button className="book-cover" onClick={()=>openBook(m.id)} aria-label={`Open ${m.title}`}><img src={m.cover} alt={`${m.short} manual cover`}/><span className="book-spine"/><span className="book-pages"/></button><div className="book-info"><span>0{i+1} · {m.pages} original pages</span><h3>{m.short}</h3><p>{m.audience}</p><div><button onClick={()=>setOverview(m.id)}>Overview</button><button className="open-link" onClick={()=>openBook(m.id)}>Open current week →</button></div></div></article>)}</div></section>
    <section className="pack-section" id="information-pack"><div className="pack-heading"><div><p className="eyebrow">Know the fellowship</p><h2>Information Pack</h2></div><p>Open the complete original TACEF information section in your preferred language.</p></div><div className="pack-grid">{Object.values(informationPacks).map(pack=><article className="pack-card" key={pack.id}><div className="pack-document" aria-hidden="true"><span>{pack.code}</span><i/></div><div><span>{pack.end-pack.start+1} original pages</span><h3>{pack.language}</h3><h4>{pack.title}</h4><p>{pack.description}</p><button onClick={()=>openInformationPack(pack.id)}>Open {pack.language} pack <b>→</b></button></div></article>)}</div></section>
    <section className="search-section" id="search"><div><p className="eyebrow">Find your manual</p><h2>Search by topic<br/>or audience</h2></div><div className="search-panel"><label htmlFor="manual-search">Search the library</label><div className="search-box"><span>⌕</span><input id="manual-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try ‘prayer’, ‘Joshua’ or ‘children’"/><button onClick={()=>setSearch("")} aria-label="Clear search">×</button></div>{search?<div className="results">{results.length?results.map(m=><button key={m.id} onClick={()=>setOverview(m.id)}><span>{m.short}</span><b>{m.subtitle}</b><small>View manual →</small></button>):<p>No matching manual found. Try a broader word.</p>}</div>:<div className="topic-chips">{["Joshua","Prayer","Children","Yorùbá","Consecration"].map(t=><button key={t} onClick={()=>setSearch(t)}>{t}</button>)}</div>}</div></section>
    <footer><div className="footer-title"><b>TACEF Books</b><span>Raising an army with a vision of revival</span></div><p>Ezekiel 37:10</p></footer>

    {overview&&<div className="modal-backdrop" onClick={()=>setOverview(null)}><article className="overview-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOverview(null)}>×</button><p className="eyebrow">Manual overview</p><h2>{manuals[overview].title}</h2><span>{manuals[overview].audience} · {manuals[overview].pages} pages · 51 weeks</span><p>{manuals[overview].overview}</p><div className="topic-list">{manuals[overview].topics.map(t=><span key={t}>{t}</span>)}</div><button className="primary" onClick={()=>openBook(overview)}>Open current week →</button></article></div>}

    {selected&&(()=>{const m=manuals[selected];const pack=readingPack?informationPacks[readingPack]:null;const minimum=pack?.start??1;const maximum=pack?.end??m.pages;return <div className="reader full-manual" role="dialog" aria-modal="true" aria-label={pack?`${pack.language} information pack`:`${m.short} complete manual reader`}>
      <div className="reader-bar"><button onClick={closeReader} className="back">← Library</button><div><b>{pack?pack.title:`${m.short} Manual`}</b><span>{pack?`${pack.language} · Pack page ${pdfPage-pack.start+1} of ${pack.end-pack.start+1}`:`Week ${week} · Original PDF page ${pdfPage} of ${m.pages}`}</span></div><a href={`${m.pdf}#page=${pdfPage}`} target="_blank" rel="noreferrer">Open original ↗</a></div>
      <div className="manual-reader-body">
        {pack?<aside className="pack-panel"><p className="eyebrow">TACEF Information Pack</p><strong>{pack.language}</strong><h2>{pack.title}</h2><p>{pack.description}</p><span>{pack.end-pack.start+1} complete original pages</span><button onClick={()=>openBook(pack.manualId)}>Open the full {pack.language} manual →</button></aside>:<aside className="week-panel"><p className="eyebrow">Browse all studies</p><label htmlFor="week-select">Select a week</label><select id="week-select" value={week} onChange={e=>{const w=Number(e.target.value);setWeek(w);goToWeek(selected,w)}}>{Array.from({length:51},(_,i)=><option key={i+1} value={i+1}>Week {i+1} — {titleForWeek(i+1)}</option>)}</select><button className="current-week" onClick={()=>goToWeek(selected,activeWeek)}>Go to current week</button><div className="week-list">{Array.from({length:51},(_,i)=><button key={i+1} className={week===i+1?"active":""} onClick={()=>goToWeek(selected,i+1)}><span>{String(i+1).padStart(2,"0")}</span><b>{titleForWeek(i+1)}</b></button>)}</div></aside>}
        <div className="pdf-book"><SinglePdfPage src={m.pdf} page={pdfPage} direction={direction} zoom={zoom}/></div>
      </div>
      <div className="reader-controls"><button onClick={()=>goToPage(pdfPage-1)} disabled={pdfPage===minimum}>← Previous page</button><div className="reader-tools"><div className="page-jump"><label htmlFor="page-number">Page</label><input id="page-number" type="number" min={pack?1:minimum} max={pack?pack.end-pack.start+1:maximum} value={pack?pdfPage-pack.start+1:pdfPage} onChange={e=>goToPage(pack?pack.start+Number(e.target.value)-1:Number(e.target.value))}/><span>of {pack?pack.end-pack.start+1:maximum}</span></div><div className="zoom-controls"><button onClick={()=>setZoom(Math.max(75,zoom-25))} aria-label="Zoom out">−</button><b>{zoom}%</b><button onClick={()=>setZoom(Math.min(200,zoom+25))} aria-label="Zoom in">+</button></div></div><button onClick={()=>goToPage(pdfPage+1)} disabled={pdfPage===maximum}>Next page →</button></div>
    </div>})()}
  </main>
}
